######################################################################
# Automatically generated by qmake (2.01a) ? 2? 6 22:58:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/CentralWidget.h \
           src/ImageWidget.h \
           src/MainWindow.h
SOURCES += src/CentralWidget.cpp \
           src/ImageWidget.cpp \
           src/Main.cpp \
           src/MainWindow.cpp
